---
title: "Untitled"
author: "Mike Alfaro"
date: "2024-04-01"
output: html_document
---

```{r warning=FALSE, message=FALSE}
# loading libraries
library(leaflet)
library(rgdal)
library(tidyverse)
```

```{r}
# Read the shapefile
WatershedConditions <- readOGR("/Users/mikea/Desktop/Capstone/StreamCond_2016_2021/StreamCond_2016_2021.shp")
WatershedConditions <- spTransform(WatershedConditions, CRS("+proj=longlat +datum=WGS84"))

Watershed_12Dig <- readOGR("/Users/mikea/Desktop/Capstone/DEP_Subwatersheds_12DIG/DEP_Subwatersheds_12DIG.shp")
Watershed_12Dig <- spTransform(Watershed_12Dig, CRS("+proj=longlat +datum=WGS84"))

```

```{r}
# Build intermap

build <- leaflet() %>% 
  addTiles(group = "OSM") %>% # Default OpenStreetMap tiles
  addProviderTiles("Esri.WorldGrayCanvas", group = "Esri.WorldGrayCanvas") %>% 
  addProviderTiles("Esri.WorldTopoMap", group = "Esri.WorldTopoMap") %>% 
  addPolygons(
    data = Watershed_12Dig,
    popup = ~as.character(MD12DIG_N),
    fillColor = NA,
    #color = "Blue",
    group = "SubWatersheds(12-DIG)"
  ) %>%
  addLayersControl(
    baseGroups = c("OSM", "Esri.WorldGrayCanvas", "Esri.WorldTopoMap"),
    overlayGroups = c("SubWatersheds (12-DIG)"),
    options = layersControlOptions(collapsed = TRUE)
  )

build

```

```{r}
names(WatershedConditions)[which(names(WatershedConditions) == "PopUp")] <- "Info"
names(WatershedConditions)[which(names(WatershedConditions) == "Narrative")] <- "Watershed_Health"
unique(WatershedConditions$Watershed_Health)
```


```{r}
# Adjusted getColor function for direct use
# provided by gpt
getColor <- function(health) {
  ifelse(health == "Excellent", "#87b3da",
         ifelse(health == "Good", "#aad691",
                ifelse(health == "Fair", "#f6f58c",
                       ifelse(health == "Poor", "#ec938d", "#8b8b8b"))))
}

```




```{r}
build2 <- build %>%
  addPolygons(
    data = WatershedConditions,
    fillColor = ~getColor(Watershed_Health), 
    color = "#BDBDC3", # Border color
    fillOpacity = 0.8,
    weight = 1,
    popup = ~paste(
      "<strong>Tributary:</strong>", Tributary, "<br/>",
      "<strong>Watershed Health:</strong>", Watershed_Health, "<br/>",
      "<strong>Info:</strong>", Info
    ),
    group = "Watershed Conditions"
  ) %>%
  addLayersControl(
    baseGroups = c("OSM", "Esri.WorldGrayCanvas", "Esri.WorldTopoMap"),
    overlayGroups = c("SubWatersheds (12-DIG)", "Watershed Conditions"),
    options = layersControlOptions(collapsed = TRUE)
  )

build2

```


```{r}
# adding snow routes 

SilverSpring <- readOGR("~/Desktop/capstone/SilverSpring_BrineRoutes/SilverSpring_BrineRoutes.shp")
SilverSpring <- spTransform(SilverSpring, CRS("+proj=longlat +datum=WGS84"))

```

```{r}

build3 <- build2 %>%  
  addPolygons(
    data = SilverSpring,
    fillColor = "gray", 
    color = "white", # Border color for the polygons
    weight = 2, # Border width
    fillOpacity = 0.8, # Transparency of the fill color
    group = "Silver Spring Routes" # The name of the toggle group in the layer control
  ) %>%
  addLayersControl(
    baseGroups = c("OSM", "Esri.WorldGrayCanvas", "Esri.WorldTopoMap"), # Keep previous base groups
    overlayGroups = c("SubWatersheds (12-DIG)", "Watershed Conditions", "Silver Spring Routes"), 
    options = layersControlOptions(collapsed = TRUE)
  )

build3

```




